# Generated by Django 4.2.16 on 2025-09-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the company searched', max_length=255, verbose_name='company name')),
                ('vat', models.CharField(help_text='VAT number of the company searched', max_length=20, verbose_name='VAT number')),
                ('color', models.CharField(help_text='Hex color code for display', max_length=7, verbose_name='color')),
                ('search_query', models.CharField(blank=True, help_text='Original search query entered by user', max_length=255, verbose_name='search query')),
                ('search_filters', models.JSONField(blank=True, default=dict, help_text='Filters applied during search', verbose_name='search filters')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='searched at')),
                ('click_count', models.IntegerField(default=1, help_text='Number of times this search result was clicked', verbose_name='click count')),
            ],
            options={
                'verbose_name': 'recent search',
                'verbose_name_plural': 'recent searches',
                'db_table': 'recent_searches',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Custom name for this saved search', max_length=100, verbose_name='search name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('query', models.CharField(blank=True, max_length=255, verbose_name='search query')),
                ('filters', models.JSONField(default=dict, help_text='Saved filter parameters', verbose_name='search filters')),
                ('is_default', models.BooleanField(default=False, help_text='Use as default search when opening search page', verbose_name='default search')),
                ('notify_new_results', models.BooleanField(default=False, help_text='Send notifications when new companies match this search', verbose_name='notify new results')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='last used')),
                ('use_count', models.IntegerField(default=0, verbose_name='use count')),
            ],
            options={
                'verbose_name': 'saved search',
                'verbose_name_plural': 'saved searches',
                'db_table': 'saved_searches',
                'ordering': ['user', '-use_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('quick', 'Quick Search'), ('advanced', 'Advanced Search'), ('vat', 'VAT Number Search'), ('name', 'Company Name Search'), ('filter', 'Filtered Search')], default='quick', max_length=20, verbose_name='search type')),
                ('query', models.TextField(verbose_name='search query')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='applied filters')),
                ('results_count', models.IntegerField(default=0, help_text='Number of results returned', verbose_name='results count')),
                ('result_clicked', models.CharField(blank=True, help_text='ID of the result clicked by user', max_length=50, verbose_name='result clicked')),
                ('response_time', models.FloatField(blank=True, help_text='Search response time in seconds', null=True, verbose_name='response time')),
                ('session_id', models.CharField(blank=True, help_text='Session identifier for grouping searches', max_length=100, verbose_name='session ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'search analytics',
                'verbose_name_plural': 'search analytics',
                'db_table': 'search_analytics',
                'ordering': ['-created_at'],
            },
        ),
    ]
