# Generated by Django 4.2.16 on 2025-09-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchanalytics",
            name="user",
        ),
        migrations.DeleteModel(
            name="SavedSearch",
        ),
        migrations.DeleteModel(
            name="SearchAnalytics",
        ),
    ]
