# Generated by Django 4.2.16 on 2025-09-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_remove_searchanalytics_user_delete_savedsearch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recentsearch",
            name="company_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the company for navigation",
                max_length=50,
                verbose_name="company ID",
            ),
        ),
    ]
