# Generated by Django 4.2.16 on 2025-09-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0004_recentsearch_company_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recentsearch",
            name="color",
        ),
    ]
