# Generated by Django 4.2.16 on 2025-09-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='group name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, choices=[('folder', 'Folder'), ('star', 'Star'), ('tag', 'Tag'), ('bookmark', 'Bookmark'), ('briefcase', 'Briefcase'), ('building', 'Building'), ('chart', 'Chart'), ('users', 'Users'), ('globe', 'Globe'), ('flag', 'Flag')], default='folder', max_length=20, verbose_name='icon')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this group is visible to other users', verbose_name='public')),
                ('color', models.CharField(blank=True, help_text='Hex color code for the group (e.g., #FF5733)', max_length=7, verbose_name='color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'company group',
                'verbose_name_plural': 'company groups',
                'db_table': 'company_groups',
                'ordering': ['owner', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('notes', models.TextField(blank=True, help_text='Notes about why this company was added to the group', verbose_name='notes')),
                ('position', models.IntegerField(default=0, help_text='Custom ordering position within the group', verbose_name='position')),
            ],
            options={
                'verbose_name': 'group membership',
                'verbose_name_plural': 'group memberships',
                'db_table': 'group_memberships',
                'ordering': ['group', 'position', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('edit', 'Can Edit'), ('admin', 'Admin')], default='view', max_length=10, verbose_name='permission')),
                ('shared_at', models.DateTimeField(auto_now_add=True, verbose_name='shared at')),
                ('notify_changes', models.BooleanField(default=True, help_text='Receive notifications when the group is modified', verbose_name='notify on changes')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='groups.companygroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'shared group',
                'verbose_name_plural': 'shared groups',
                'db_table': 'shared_groups',
                'ordering': ['-shared_at'],
            },
        ),
    ]
