# Generated by Django 4.2.16 on 2025-09-01 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedgroup',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_shared', to=settings.AUTH_USER_MODEL, verbose_name='shared by'),
        ),
        migrations.AddField(
            model_name='sharedgroup',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_groups', to=settings.AUTH_USER_MODEL, verbose_name='shared with'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_additions', to=settings.AUTH_USER_MODEL, verbose_name='added by'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.companygroup', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='companygroup',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='groups', through='groups.GroupMembership', to='companies.company', verbose_name='companies'),
        ),
        migrations.AddField(
            model_name='companygroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_groups', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterUniqueTogether(
            name='sharedgroup',
            unique_together={('group', 'shared_with')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='companygroup',
            unique_together={('owner', 'name')},
        ),
    ]
