# Generated by Django 4.2.16 on 2025-09-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companygroup",
            name="is_public",
        ),
    ]
