# Generated by Django 4.2.16 on 2025-09-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_remove_is_public"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SharedGroup",
        ),
    ]
