# Generated by Django 4.2.16 on 2025-09-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_remove_shared_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companygroup",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("competitive", "Concurrence"),
                    ("partnership", "Partenariat"),
                    ("supplier", "Fournisseur"),
                    ("client", "Client"),
                    ("finance", "Finance"),
                    ("technology", "Technologie"),
                    ("manufacturing", "Production"),
                    ("services", "Services"),
                    ("folder", "Dossier"),
                ],
                default="folder",
                max_length=20,
                verbose_name="icon",
            ),
        ),
    ]
