# Generated by Django 4.2.16 on 2025-09-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0006_remove_color_notes_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembership",
            name="position",
            field=models.IntegerField(
                default=0,
                help_text="Position in the group for custom ordering",
                verbose_name="position",
            ),
        ),
    ]
