# Generated by Django 4.2.16 on 2025-09-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0007_add_position_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companygroup",
            options={
                "ordering": ["owner", "position", "name"],
                "verbose_name": "company group",
                "verbose_name_plural": "company groups",
            },
        ),
        migrations.AddField(
            model_name="companygroup",
            name="position",
            field=models.IntegerField(
                default=0,
                help_text="Position for custom ordering",
                verbose_name="position",
            ),
        ),
    ]
