# Generated by Django 4.2.16 on 2025-09-01 13:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(help_text='Unique identifier for the company', max_length=50, primary_key=True, serialize=False, verbose_name='company ID')),
                ('vat', models.CharField(help_text='Belgian VAT number (BE + 10 digits)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='VAT number must be in format BE0123456789', regex='^BE\\d{10}$')], verbose_name='VAT number')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='company name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('dissolved', 'Dissolved'), ('bankrupt', 'Bankrupt')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('legal_form', models.CharField(blank=True, choices=[('SA', 'SA - Société Anonyme'), ('SRL', 'SRL - Société à Responsabilité Limitée'), ('SPRL', 'SPRL - Société Privée à Responsabilité Limitée'), ('SC', 'SC - Société Coopérative'), ('SNC', 'SNC - Société en Nom Collectif'), ('SCS', 'SCS - Société en Commandite Simple'), ('ASBL', 'ASBL - Association Sans But Lucratif'), ('AISBL', 'AISBL - Association Internationale Sans But Lucratif'), ('OTHER', 'Other')], max_length=20, verbose_name='legal form')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='creation date')),
                ('fiscal_year', models.CharField(blank=True, help_text='Fiscal year end date (e.g., 31/12)', max_length=20, verbose_name='fiscal year')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('capital', models.CharField(blank=True, max_length=50, verbose_name='capital')),
                ('employees', models.IntegerField(blank=True, null=True, verbose_name='number of employees')),
                ('nace_codes', models.JSONField(blank=True, default=list, help_text='List of NACE activity codes', verbose_name='NACE codes')),
                ('activity', models.TextField(blank=True, verbose_name='activity description')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='sector')),
                ('company_type', models.CharField(blank=True, max_length=50, verbose_name='company type')),
                ('company_size', models.CharField(blank=True, choices=[('micro', 'Micro (1-9 employees)'), ('small', 'Small (10-49 employees)'), ('medium', 'Medium (50-249 employees)'), ('large', 'Large (250+ employees)')], max_length=20, verbose_name='company size')),
                ('company_description', models.TextField(blank=True, verbose_name='company description')),
                ('region', models.CharField(blank=True, choices=[('flanders', 'Flanders'), ('wallonia', 'Wallonia'), ('brussels', 'Brussels')], db_index=True, max_length=20, verbose_name='region')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='city')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='street')),
                ('street_number', models.CharField(blank=True, max_length=20, verbose_name='street number')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postal code')),
                ('country', models.CharField(default='BE', max_length=2, verbose_name='country')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='year')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='revenue')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='profit')),
                ('margin', models.DecimalField(blank=True, decimal_places=2, help_text='Profit margin as percentage', max_digits=5, null=True, verbose_name='margin')),
                ('employees', models.IntegerField(blank=True, null=True, verbose_name='number of employees')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional financial metrics', verbose_name='additional data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'financial data',
                'verbose_name_plural': 'financial data',
                'db_table': 'financial_data',
                'ordering': ['company', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text='KBO unit number', max_length=50, verbose_name='unit number')),
                ('name', models.CharField(max_length=255, verbose_name='establishment name')),
                ('type', models.CharField(choices=[('headquarters', 'Headquarters'), ('branch', 'Branch'), ('production', 'Production Site'), ('warehouse', 'Warehouse'), ('office', 'Office'), ('retail', 'Retail Location')], default='branch', max_length=20, verbose_name='type')),
                ('street', models.CharField(max_length=255, verbose_name='street')),
                ('street_number', models.CharField(max_length=20, verbose_name='street number')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('postal_code', models.CharField(max_length=10, verbose_name='postal code')),
                ('country', models.CharField(default='BE', max_length=2, verbose_name='country')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('employees', models.IntegerField(blank=True, null=True, verbose_name='number of employees')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='creation date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'establishment',
                'verbose_name_plural': 'establishments',
                'db_table': 'establishments',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_since', models.DateTimeField(auto_now_add=True, verbose_name='followed since')),
                ('notify_updates', models.BooleanField(default=True, help_text='Receive notifications when company data is updated', verbose_name='notify on updates')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'company follower',
                'verbose_name_plural': 'company followers',
                'db_table': 'company_followers',
                'ordering': ['-followed_since'],
            },
        ),
    ]
