# Generated by Django 4.2.16 on 2025-09-01 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfollower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_companies', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['vat'], name='companies_vat_1ac6f8_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status', 'region'], name='companies_status_57bdce_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name', 'status'], name='companies_name_30c4e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financialdata',
            unique_together={('company', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='establishment',
            unique_together={('company', 'unit_number')},
        ),
        migrations.AlterUniqueTogether(
            name='companyfollower',
            unique_together={('user', 'company')},
        ),
    ]
