# Generated by Django 4.2.16 on 2025-09-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="establishment",
            name="email",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="employees",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="type",
        ),
    ]
