# Generated by Django 4.2.16 on 2025-09-22 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_remove_establishment_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nacebel_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of NACEBEL activity codes",
                        verbose_name="NACEBEL codes",
                    ),
                ),
                (
                    "company_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of company activities",
                        verbose_name="company activities",
                    ),
                ),
                (
                    "sectors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of business sectors",
                        verbose_name="sectors",
                    ),
                ),
                (
                    "services",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of services offered",
                        verbose_name="services",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of company activities",
                        verbose_name="activity description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="companies.company",
                        verbose_name="company",
                    ),
                ),
            ],
            options={
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
                "db_table": "company_activities",
            },
        ),
    ]
