# Generated by Django 4.2.15 on 2025-01-23 00:52

from django.db import migrations

def migrate_activity_data(apps, schema_editor):
    """Migrate activity data from Company model to Activity model."""
    Company = apps.get_model('companies', 'Company')
    Activity = apps.get_model('companies', 'Activity')
    
    for company in Company.objects.all():
        # Create Activity object for each company
        activity = Activity.objects.create(
            company=company,
            nacebel_codes=company.nace_codes if company.nace_codes else [],
            description=company.activity if company.activity else '',
        )
        
        # Convert sector to list
        if company.sector:
            activity.sectors = [company.sector]
        else:
            activity.sectors = []
            
        # Use company_description as part of company_activities
        if company.company_description:
            activity.company_activities = [company.company_description]
        else:
            activity.company_activities = []
            
        # Initialize services as empty for now
        activity.services = []
        
        activity.save()

def reverse_migrate_activity_data(apps, schema_editor):
    """Reverse migration - move data back to Company model."""
    Company = apps.get_model('companies', 'Company')
    Activity = apps.get_model('companies', 'Activity')
    
    for activity in Activity.objects.all():
        company = activity.company
        
        # Move data back
        company.nace_codes = activity.nacebel_codes
        company.activity = activity.description
        
        # Take first sector if available
        if activity.sectors:
            company.sector = activity.sectors[0]
            
        # Take first activity as description
        if activity.company_activities:
            company.company_description = activity.company_activities[0]
            
        company.save()
    
    # Delete all Activity objects
    Activity.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_add_activity_model'),
    ]

    operations = [
        migrations.RunPython(
            migrate_activity_data,
            reverse_migrate_activity_data
        ),
    ]