# Generated by Django 4.2.16 on 2025-09-22 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_migrate_activity_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_description",
        ),
        migrations.RemoveField(
            model_name="company",
            name="nace_codes",
        ),
        migrations.RemoveField(
            model_name="company",
            name="sector",
        ),
    ]
