# Generated by Django 4.2.16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_old_activity_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='street')),
                ('street_number', models.CharField(blank=True, max_length=20, verbose_name='street number')),
                ('postal_box', models.CharField(blank=True, help_text='e.g., Box 12, Boite 5', max_length=50, verbose_name='postal box')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postal code')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='province')),
                ('region', models.CharField(blank=True, choices=[('flanders', 'Flanders'), ('wallonia', 'Wallonia'), ('brussels', 'Brussels')], max_length=20, verbose_name='region')),
                ('country', models.CharField(default='BE', max_length=2, verbose_name='country')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'db_table': 'addresses',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='companies.address', verbose_name='address'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='establishment', to='companies.address', verbose_name='address'),
        ),
    ]