# Generated by Django 4.2.16

from django.db import migrations


def migrate_address_data(apps, schema_editor):
    """Migrate address data from Company and Establishment to Address model."""
    Company = apps.get_model('companies', 'Company')
    Establishment = apps.get_model('companies', 'Establishment')
    Address = apps.get_model('companies', 'Address')
    
    # Migrate company addresses
    for company in Company.objects.all():
        if any([company.street, company.street_number, company.postal_code, company.city]):
            address = Address.objects.create(
                street=company.street or '',
                street_number=company.street_number or '',
                postal_code=company.postal_code or '',
                city=company.city or '',
                region=company.region or '',
                country=company.country or 'BE'
            )
            company.address = address
            company.save()
    
    # Migrate establishment addresses
    for establishment in Establishment.objects.all():
        if any([establishment.street, establishment.street_number, establishment.postal_code, establishment.city]):
            address = Address.objects.create(
                street=establishment.street or '',
                street_number=establishment.street_number or '',
                postal_code=establishment.postal_code or '',
                city=establishment.city or '',
                country=establishment.country or 'BE'
            )
            establishment.address = address
            establishment.save()


def reverse_migrate_address_data(apps, schema_editor):
    """Reverse migration - copy data back from Address to Company/Establishment."""
    Company = apps.get_model('companies', 'Company')
    Establishment = apps.get_model('companies', 'Establishment')
    
    # Copy company addresses back
    for company in Company.objects.filter(address__isnull=False):
        company.street = company.address.street
        company.street_number = company.address.street_number
        company.postal_code = company.address.postal_code
        company.city = company.address.city
        company.region = company.address.region
        company.country = company.address.country
        company.save()
    
    # Copy establishment addresses back
    for establishment in Establishment.objects.filter(address__isnull=False):
        establishment.street = establishment.address.street
        establishment.street_number = establishment.address.street_number
        establishment.postal_code = establishment.address.postal_code
        establishment.city = establishment.address.city
        establishment.country = establishment.address.country
        establishment.save()
    
    # Delete all Address objects
    Address = apps.get_model('companies', 'Address')
    Address.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_add_address_model'),
    ]

    operations = [
        migrations.RunPython(
            migrate_address_data,
            reverse_migrate_address_data
        ),
    ]