# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_migrate_address_data'),
    ]

    operations = [
        # Remove old address fields from Company
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.RemoveField(
            model_name='company',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='region',
        ),
        migrations.RemoveField(
            model_name='company',
            name='street',
        ),
        migrations.RemoveField(
            model_name='company',
            name='street_number',
        ),
        # Remove old address fields from Establishment
        migrations.RemoveField(
            model_name='establishment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='country',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='street',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='street_number',
        ),
        # Add new index for Company without region
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status'], name='companies_c_status_2cde5e_idx'),
        ),
    ]