# Generated by Django 4.2.16 on 2025-09-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_remove_old_address_fields"),
    ]

    operations = [
        # Remove old indexes that exist
        migrations.RemoveIndex(
            model_name="company",
            name="companies_name_30c4e4_idx",
        ),
        # The companies_c_status_2cde5e_idx index already exists, no need to rename
        # Just add the new name index
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["name"], name="companies_name_c7a1b3_idx"),
        ),
    ]
