# Generated by Django 4.2.16 on 2025-10-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0012_increase_country_field_length"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="company",
            name="companies_status_57bdce_idx",
        ),
        migrations.RenameIndex(
            model_name="company",
            new_name="companies_status_2cde5e_idx",
            old_name="companies_c_status_2cde5e_idx",
        ),
        migrations.AlterField(
            model_name="company",
            name="legal_form",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="legal form",
                choices=[
                    ("SA", "SA - Société Anonyme"),
                    ("SRL", "SRL - Société à Responsabilité Limitée"),
                    ("SPRL", "SPRL - Société Privée à Responsabilité Limitée"),
                    ("SC", "SC - Société Coopérative"),
                    ("SNC", "SNC - Société en Nom Collectif"),
                    ("SCS", "SCS - Société en Commandite Simple"),
                    ("ASBL", "ASBL - Association Sans But Lucratif"),
                    ("AISBL", "AISBL - Association Internationale Sans But Lucratif"),
                    ("OTHER", "Other"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="phone"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="website"),
        ),
    ]
