# Generated by Django 4.2.16 on 2025-10-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0013_increase_legal_form_and_phone_field_lengths"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialdata",
            name="total_assets",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total balance sheet assets",
                max_digits=15,
                null=True,
                verbose_name="total assets",
            ),
        ),
    ]
