# Generated by Django 4.2.16 on 2025-10-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0014_financialdata_total_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialdata",
            name="gross_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Gross margin in EUR",
                max_digits=15,
                null=True,
                verbose_name="gross margin",
            ),
        ),
    ]
